[project]
name = "AgentOperatingSystem"
version = "0.1.0"
dependencies = [
    "semantic-kernel",
    "asyncio",
    "python-dotenv",
    "azure-search-documents",
    "fastapi",
    "pandas",
    "uvicorn",
    "streamlit",
    "opentelemetry-api",
    "opentelemetry-sdk",
    "opentelemetry-exporter-otlp-proto-grpc",
    "opentelemetry-instrumentation-fastapi",
    "PurposeDrivenAgent @ git+https://github.com/ASISaga/PurposeDrivenAgent.git",
    "FineTunedLLM @ git+https://github.com/ASISaga/FineTunedLLM.git"
]
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
